about/urls.py
from django.urls import path
from . import views


app_name = 'about'
urlpatterns = [
    path('', views.about, name='about'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('about/', include('about.urls')),
    path('skating/', include('skating.urls')),
    path('shop/', include('shop.urls')),
    path('contact/', include('contact.urls')),
    path('product/', include('product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact'),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('', views.product, name='product'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.shop, name='shop'),
]

skating/urls.py
from django.urls import path
from . import views


app_name = 'skating'
urlpatterns = [
    path('', views.skating, name='skating'),
]

about/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    color = models.CharField(max_length=25)
    size = models.IntegerField(default=1)
    count = models.IntegerField(default=1)
    image = models.ImageField(upload_to='product/images/')

    class Meta:
        verbose_name = "Mahsulot"
        verbose_name_plural = "Mahsulotlar"

    def __str__(self):
        return str(self.title)

shop/models.py
from django.db import models

# Create your models here.

skating/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render


def about(request):
    context = {
        "title": 'About sahifasi'
    }
    return render(request, 'about.html', context)

contact/views.py
from django.shortcuts import render


def contact(request):
    context = {
        "title": 'Contact sahifasi'
    }
    return render(request, 'contact.html', context)

main/views.py
from django.shortcuts import render


def index(request):
    context = {
        "title": 'Bosh sahifa'
    }
    return render(request, 'index.html', context)

product/views.py
from django.shortcuts import render
from .models import Product


def product(request):
    products = Product.objects.all()
    context = {
        "title": 'Product sahifasi Qo\'shimcha',
        'products': products,
        'count': len(products),
    }
    return render(request, 'product.html', context)

shop/views.py
from django.shortcuts import render


def shop(request):
    context = {
        "title": 'Shop sahifasi'
    }
    return render(request, 'shop.html', context)

skating/views.py
from django.shortcuts import render


def skating(request):
    context = {
        "title": 'Skating sahifasi'
    }
    return render(request, 'skating.html', context)

templates/about.html
{% extends 'base.html' %}


{% block title %}
	{{ title }}
{% endblock %}


{% block content %}
    <!-- top -->
    <!-- about -->
    {% include 'components/about.html' %}
    <!-- end about -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
      <!-- basic -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- mobile metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        <!-- site metas -->
        <title>
            {% block title %}
            
            {% endblock %}
        </title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- bootstrap css -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- style css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Responsive-->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <!-- fevicon -->
        <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
        <!-- Tweaks for older IEs-->
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    </head>
    <!-- body -->
    <body class="main-layout">
        <!-- loader  -->
        <div class="loader_bg">
            <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#"/></div>
        </div>
          <!-- end loader -->
          <!-- header -->
        {% include 'components/header.html' %}
          <!-- end header inner -->
          <!-- end header -->
          <!-- top -->
        {% include 'components/full_bg.html' %}
        <!-- end banner -->
      
        {% block content %}
        
        {% endblock %}
      
        <!--  footer -->
        {% include 'components/footer.html' %}
          <!-- end footer -->
          <!-- Javascript files-->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
        <!-- sidebar -->
        <script src="{% static 'js/custom.js' %}"></script>
        <script>
            AOS.init();
        </script>
   </body>
</html>

templates/components/about.html
{% load static %}


<div class="about">
    <div class="container-fluid">
        <div class="row d_flex">
           <div class="col-md-6">
              <div class="titlepage text_align_left">
                 <h2>About <br>Skating <br> school</h2>
                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variatioThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variationsns
                 </p>
                 <div class="link_btn">
                    <a class="read_more" href="{% url 'about:about' %}">Read More</a>
                 </div>
              </div>
           </div>
           <div class="col-md-6">
              <div class="about_img text_align_center">
                 <figure><img src="{% static 'images/about.png' %}" alt="#"/></figure>
              </div>
           </div>
        </div>
    </div>
</div>

templates/components/class.html
{% load static %}


<div class="class">
    <div class="container">
        <div class="row">
           <div class="col-md-12">
              <div class="titlepage text_align_center">
                 <h2>Our Skating Class</h2>
                 <p>There are many variations of passages of Lorem</p>
              </div>
           </div>
        </div>
        <div class="row">
           <div class="col-md-4 margi_bottom">
              <div class="class_box text_align_center">
                 <i><img src="{% static 'images/class1.png' %}" alt="#"/></i>
                 <h3>Skateboard</h3>
                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variations </p>
              </div>
              <a class="read_more" href="Javascript:void(0)">Read More</a>
           </div>
           <div class="col-md-4 margi_bottom">
              <div class="class_box blue text_align_center">
                 <i><img src="{% static 'images/class2.png' %}" alt="#"/></i>
                 <h3>Skateboard</h3>
                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variations </p>
              </div>
              <a class="read_more" href="Javascript:void(0)">Read More</a>
           </div>
           <div class="col-md-4 margi_bottom">
              <div class="class_box text_align_center">
                 <i><img src="{% static 'images/class3.png' %}" alt="#"/></i>
                 <h3>Skateboard</h3>
                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variations </p>
              </div>
              <a class="read_more" href="Javascript:void(0)">Read More</a>
           </div>
        </div>
    </div>
</div>

templates/components/contact.html
{% load static %}


<div class="contact">
    <div class="container">
        <div class="row ">
           <div class="col-md-12">
              <div class="titlepage text_align_center">
                 <h2>Contact Us</h2>
              </div>
           </div>
           <div class="col-md-6">
              <form id="request" class="main_form">
                 <div class="row">
                    <div class="col-md-6 ">
                       <input class="contactus" placeholder="Name*" type="type" name=" Name"> 
                    </div>
                    <div class="col-md-6">
                       <input class="contactus" placeholder="Phone Number*" type="type" name="Phone Number">                          
                    </div>
                    <div class="col-md-12">
                       <input class="contactus" placeholder="Email*" type="type" name="Email">                          
                    </div>
                    <div class="col-md-12 select-outline">
                       <select class="custom-select ">
                          <option selected>Select Subject*</option>
                          <option value="1">a</option>
                          <option value="2">b</option>
                          <option value="3">c</option>
                       </select>
                    </div>
                    <div class="col-md-12">
                       <textarea class="textarea" placeholder="Message" type="type" Message="Name"></textarea>
                    </div>
                    <div class="col-md-12">
                       <button class="send_btn">Send</button>
                    </div>
                 </div>
              </form>
           </div>
           <div class="col-md-6">
              <div class="map_main">
                 <div class="map-responsive">
                    <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&amp;q=Eiffel+Tower+Paris+France" width="600" height="450" frameborder="0" style="border:0; width: 100%;" allowfullscreen=""></iframe>
                 </div>
              </div>
           </div>
        </div>
    </div>
</div>

templates/components/footer.html
{% load static %}


<footer>
    <div class="footer">
        <div class="container">
           <div class="row">
              <div class="col-md-4 ">
                 <div class="infoma">
                    <h3>Contact Us</h3>
                    <ul class="conta">
                       <li><i class="fa fa-map-marker" aria-hidden="true"></i>Locations
                       </li>
                       <li><i class="fa fa-phone" aria-hidden="true"></i>Call +01 1234567890</li>
                       <li> <i class="fa fa-envelope" aria-hidden="true"></i><a href="Javascript:void(0)"> demo@gmail.com</a></li>
                    </ul>
                 </div>
              </div>
              <div class="col-md-8">
                 <div class="row border_left">
                    <div class="col-md-12">
                       <div class="infoma">
                          <h3>Newsletter</h3>
                          <form class="form_subscri">
                             <div class="row">
                                <div class="col-md-12">
                                </div>
                                <div class="col-md-4">
                                   <input class="newsl" placeholder="Enter your email" type="text" name="Enter your email">
                                </div>
                                <div class="col-md-4">
                                   <button class="subsci_btn">subscribe</button>
                                </div>
                             </div>
                          </form>
                       </div>
                    </div>
                    <div class="col-md-9">
                       <div class="infoma">
                          <h3>Useful Link</h3>
                          <ul class="fullink">
                             <li><a href="{% url 'main:index' %}">Home</a></li>
                             <li><a href="{% url 'about:about' %}">About</a></li>
                             <li><a href="{% url 'skating:skating' %}">Skating</a></li>
                             <li><a href="{% url 'shop:shop' %}">Shop</a></li>
                             <li><a href="{% url 'contact:contact' %}">Contact Us</a></li>
                             <li><a href="{% url 'product:product' %}">Product</a></li>
                          </ul>
                       </div>
                    </div>
                    <div class="col-md-3">
                       <div class="infoma text_align_left">
                          <ul class="social_icon">
                             <li><a href="Javascript:void(0)"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                             <li><a href="Javascript:void(0)"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                             <li><a href="Javascript:void(0)"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                             <li><a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                          </ul>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="copyright">
           <div class="container">
              <div class="row">
                 <div class="col-md-12">
                    <p>© 2020 All Rights Reserved. Design by <a href="https://html.design/" target="_blank"> Free html Templates</a></p>
                 </div>
              </div>
           </div>
        </div>
    </div>
</footer>

templates/components/full_bg.html
{% load static %}


<div class="full_bg">
    <div class="slider_main">
        <div class="container-fluid">
           <div class="row">
              <div class="col-md-12">
                 <!-- carousel code -->
                 <div id="carouselExampleIndicators" class="carousel slide">
                    <ol class="carousel-indicators">
                       <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                       <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                       <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                       <!-- first slide -->
                       <div class="carousel-item active">
                          <div class="carousel-caption relative">
                             <div class="row d_flex">
                                <div  class="col-md-5">
                                   <div class="board">
                                      <i><img src="{% static 'images/top_icon.png' %}" alt="#"/></i>
                                      <h3>
                                          {{ title }}
                                      </h3>
                                      <div class="link_btn">
                                         <a class="read_more" href="Javascript:void(0)">Read More   <span></span></a>
                                      </div>
                                   </div>
                                </div>
                                <div class="col-md-7">
                                   <div class="banner_img">
                                      <figure><img class="img_responsive" src="{% static 'images/banner_img.png' %}"></figure>
                                   </div>
                                </div>
                             </div>
                          </div>
                       </div>
                       <!-- second slide -->
                       <div class="carousel-item">
                          <div class="carousel-caption relative">
                             <div class="row d_flex">
                                <div  class="col-md-5">
                                   <div class="board">
                                      <i><img src="{% static 'images/top_icon.png' %}" alt="#"/></i>
                                      <h3>
                                         {{ title }}
                                      </h3>
                                      <div class="link_btn">
                                         <a class="read_more" href="Javascript:void(0)">Read More   <span></span></a>
                                      </div>
                                   </div>
                                </div>
                                <div class="col-md-7">
                                   <div class="banner_img">
                                      <figure><img class="img_responsive" src="{% static 'images/banner_img.png' %}"></figure>
                                   </div>
                                </div>
                             </div>
                          </div>
                       </div>
                       <!-- third slide-->
                       <div class="carousel-item">
                          <div class="carousel-caption relative">
                             <div class="row d_flex">
                                <div  class="col-md-5">
                                   <div class="board">
                                      <i><img src="{% static 'images/top_icon.png' %}" alt="#"/></i>
                                      <h3>
                                         {{ title }}
                                      </h3>
                                      <div class="link_btn">
                                         <a class="read_more" href="Javascript:void(0)">Read More   <span></span></a>
                                      </div>
                                   </div>
                                </div>
                                <div class="col-md-7">
                                   <div class="banner_img">
                                      <figure><img class="img_responsive" src="{% static 'images/banner_img.png' %}"></figure>
                                   </div>
                                </div>
                             </div>
                          </div>
                       </div>
                    </div>
                    <!-- controls -->
{#                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">#}
{#                    <i class="fa fa-arrow-left" aria-hidden="true"></i>#}
{#                    <span class="sr-only">Previous</span>#}
{#                    </a>#}
{#                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">#}
{#                    <i class="fa fa-arrow-right" aria-hidden="true"></i>#}
{#                    <span class="sr-only">Next</span>#}
{#                    </a>#}
                 </div>
              </div>
           </div>
        </div>
    </div>
</div>

templates/components/header.html
{% load static %}


<div class="header">
    <div class="container-fluid">
        <div class="row d_flex">
           <div class=" col-md-2 col-sm-3 col logo_section">
              <div class="full">
                 <div class="center-desk">
                    <div class="logo">
                       <a href="{% url 'main:index' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                    </div>
                 </div>
              </div>
           </div>
           <div class="col-md-8 col-sm-12">
              <nav class="navigation navbar navbar-expand-md navbar-dark ">
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                 <span class="navbar-toggler-icon"></span>
                 </button>
                 <div class="collapse navbar-collapse" id="navbarsExample04">
                     {% with request.resolver_match.app_name as app_name %}
                        <ul class="navbar-nav mr-auto">
                           <li class="nav-item {% if app_name == 'main' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                           </li>
                           <li class="nav-item {% if app_name == 'about' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'about:about' %}">About</a>
                           </li>
                           <li class="nav-item {% if app_name == 'skating' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'skating:skating' %}">skating</a>
                           </li>
                           <li class="nav-item {% if app_name == 'shop' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'shop:shop' %}">shop</a>
                           </li>
                           <li class="nav-item {% if app_name == 'contact' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
                           </li>
                           <li class="nav-item {% if app_name == 'product' %}active{% endif %}">
                              <a class="nav-link" href="{% url 'product:product' %}">Products <sup><i class="fa fa-star"></i></sup></a>
                           </li>
                        </ul>
                     {% endwith %}
                 </div>
              </nav>
           </div>
           <div class="col-md-2">
              <ul class="email text_align_right">
                 <li class="d_none"><a href="Javascript:void(0)"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                 <li class="d_none"> <a href="Javascript:void(0)"><i class="fa fa-search" style="cursor: pointer;" aria-hidden="true"></i></a> </li>
              </ul>
           </div>
        </div>
    </div>
</div>

templates/components/product.html
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12 pt-3">
            <div class="titlepage text_align_center">
                <h2>Mahsulotlar ({{ count }})</h2>
            </div>
        </div>
        {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top">
                        <h1 class="card-title">{{ product.title }}</h1>
                        <p class="card-price">${{ product.price }}</p>
                        <p class="card-sizes">Sizes: {{ product.size }}</p>
                        <p class="card-sizes">Count: {{ product.count }}</p>
                        <p class="card-colors">Colors:
                            {{ product.color }} <span style="background-color: {{ product.color }}; width: 20px; height: 20px; display: inline-block; border-radius: 50%; border: 1px solid black"></span>
                        </p>
                        <a href="#" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>


<style>
    /* styles.css */
.card {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    text-align: center;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 10px;
    overflow: hidden;
    transition: transform 0.2s;
}

.card:hover {
    transform: scale(.90);
}

.card-img-top {
    width: 200px;
    height: 300px;
}

.card-body {
    padding: 20px;
}

.card-price {
    font-size: 1.25rem;
    color: #48cfad;
}

.card-sizes, .card-colors {
    margin-top: 10px;
}

.card-colors span {
    margin-right: 5px;
}

</style>

templates/components/shop.html
{% load static %}


<div class="shop">
    <div class="container-fluid">
        <div class="row d_flex d_grid">
           <div class="col-md-7">
              <div class="shop_img text_align_center" data-aos="fade-right">
                 <figure><img class="img_responsive" src="{% static 'images/shop.png' %}" alt="#"/></figure>
              </div>
           </div>
           <div class="col-md-5 order_1_mobile">
              <div class="titlepage text_align_left ">
                 <h2>Our  Skate <br>Shop</h2>
                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variatioThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alterationThere are many variationsns
                 </p>
                 <a class="read_more" href="{% url 'shop:shop' %}">Buy Now</a>
              </div>
           </div>
        </div>
    </div>
</div>

templates/components/skatching.html
{% load static %}


<div class="skating">
    <div class="container-fluid">
        <div class="row">
           <div class="col-md-12">
              <div class="titlepage text_align_center">
                 <h2>Skating  Video</h2>
                 <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                 </p>
              </div>
           </div>
        </div>
        <div class="row">
           <div class="col-md-4">
              <div class="skating-box ">
                 <figure><img src="{% static 'images/sakt1.png' %}" alt="#"/></figure>
                 <div class="link_btn">
                    <a class="read_more" href="Javascript:void(0)">See More</a>
                 </div>
              </div>
           </div>
           <div class="col-md-4">
              <div class="skating-box">
                 <figure><img src="{% static 'images/sakt2.png' %}" alt="#"/></figure>
                 <div class="link_btn">
                    <a class="read_more" href="Javascript:void(0)">See More</a>
                 </div>
              </div>
           </div>
           <div class="col-md-4">
              <div class="skating-box">
                 <figure><img src="{% static 'images/sakt3.png' %}" alt="#"/></figure>
                 <div class="link_btn">
                    <a class="read_more" href="Javascript:void(0)">See More</a>
                 </div>
              </div>
           </div>
        </div>
    </div>
</div>

templates/contact.html
{% extends 'base.html' %}


{% block title %}
	{{ title }}
{% endblock %}


{% block content %}
    
    <!-- contact -->
    {% include 'components/contact.html' %}
    <!-- end contact -->
{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block title %}
	{{ title }}
{% endblock %}


{% block content %}
    
    <!-- our class -->
    {% include 'components/class.html' %}
    <!-- end our class -->
    <!-- about -->
    {% include 'components/about.html' %}
    <!-- end about -->
    <!-- skating -->
    {% include 'components/skatching.html' %}
    <!-- end skating -->
    <!-- shop -->
    {% include 'components/shop.html' %}
    <!-- end shop -->
    <!-- testimonial -->
    {% include 'components/testimonial.html' %}
    <!-- end testimonial -->
{% endblock %}

templates/product.html
{% extends 'base.html' %}


{% block title %}
	{{ title }} product
{% endblock %}


{% block content %}
    
    <!-- our class -->
    {% include 'components/product.html' %}
    <!-- end our class -->
{% endblock %}

templates/shop.html
{% extends 'base.html' %}


{% block title %}
	{{ title }}
{% endblock %}


{% block content %}
    <!-- shop -->
    {% include 'components/shop.html' %}
    <!-- end shop -->
{% endblock %}

templates/skating.html
{% extends 'base.html' %}


{% block title %}
	{{ title }}
{% endblock %}


{% block content %}
    <!-- skating -->
    {% include 'components/skatching.html' %}
    <!-- end skating -->
{% endblock %}